# Generated by Django 3.1.7 on 2021-06-10 10:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0015_externaltools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seolink',
            name='content',
            field=tinymce.models.HTMLField(default='pas de contenu..'),
        ),
    ]
