# Generated by Django 3.1.7 on 2021-06-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0017_auto_20210612_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='/no_image.jpg', upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='new',
            name='post_image',
            field=models.ImageField(default='/no_image.jpg', upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.ImageField(default='/no_service.jpg', upload_to='article/'),
        ),
    ]
