# Generated by Django 3.1.7 on 2021-09-08 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0018_auto_20210628_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(default='/no_image.jpg', upload_to='theme/')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slogan', models.CharField(default='Xerixy CMS', max_length=50)),
                ('subSlogan', models.CharField(default='Your CMS to make websites easily', max_length=50)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.banner')),
            ],
        ),
        migrations.DeleteModel(
            name='License',
        ),
    ]
