# Generated by Django 3.1.7 on 2021-09-08 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0019_auto_20210908_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='banner',
        ),
        migrations.AddField(
            model_name='banner',
            name='Theme',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='root.theme'),
            preserve_default=False,
        ),
    ]
