# Generated by Django 3.1.7 on 2021-09-08 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0021_remove_banner_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='root.theme'),
            preserve_default=False,
        ),
    ]
